Repository boostcampwm-2021/web14-salondesrefuses, pull requests merged in 2021-11, with the labels that each got.

#71 feat: 모바일/PC 분기하는 작업 - #70
  client/components/Home/Mobile.tsx
  client/components/Home/Pc.tsx
  client/components/common/DeviceSwitch.tsx
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/utils/isMobile.ts
  package-lock.json
Labels: 🚀 Front, Priority: High

#73 Feat/#72 setting emotion
  client/pages/_app.tsx
  client/styles/common.ts
  client/styles/emtion.d.ts
  client/styles/globals.css
  client/styles/theme.ts
Labels: 🚀 Front, Priority: High

#74 feat: TypeORM 엔티티 구현 - #69
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/artWork/artWork.entity.ts
  server/src/artwork/artwork.entity.ts
  server/src/artwork/artwork.status.enum.ts
  server/src/artworkInBid/artworkInBid.entity.ts
  server/src/auction/auction.entity.ts
  server/src/auctionHistory/auctionHistory.entity.ts
  server/src/category/category.entity.ts
  server/src/config/typeorm.config.ts
  server/src/exhibition/exhibition.entity.ts
  server/src/interestArtwork/interestArtwork.entity.ts
  server/src/user/user.entity.ts
Labels: 🛰 Back, Priority: High

#77 feat: Artwork 추가(등록) 페이지 구현 - #55
  client/components/Artwork/ArtworkModal/ArtworkFilter.tsx
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/ArtworkModal/style.ts
  client/components/Artwork/NewArtwork/index.tsx
  client/components/Artwork/NewArtwork/style.ts
  client/components/Artwork/Tiles/index.tsx
  client/components/Artwork/Uploader/index.tsx
  client/components/common/Layout.tsx
  client/hooks/useControlModalPosition.ts
  client/hooks/useInputArtwork.ts
  client/hooks/usePreviewImage.ts
  client/pages/artwork/post.tsx
  client/public/icons/add.png
  client/public/icons/check_green.png
  client/public/icons/check_grey.png
  client/styles/common.ts
  client/styles/emtion.d.ts
  client/styles/globals.css
  server/package-lock.json
  server/src/auction/auction.entity.ts
  server/src/exhibition/controller/exhibition.controller.ts
  server/src/main.ts
Labels: 🚀 Front, Priority: High

#82 feat: mobile 페이지 생성 - #70
  client/assets/images/tmpLogo.png
  client/components/Home/Mobile/index.tsx
  client/components/Home/Mobile/styles.ts
  client/styles/common.ts
Labels: 🚀 Front, Priority: Low

#78 feat: artwork post API 기능 개발 - #68
  .gitignore
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/artWork/artWork.module.ts
  server/src/artWork/artWork.repository.ts
  server/src/artWork/controller/artWork.controller.ts
  server/src/artWork/dto/artworkDTOs.ts
  server/src/artWork/dto/imageDTOs.ts
  server/src/artWork/service/artWork.service.ts
  server/src/artwork/artwork.entity.ts
  server/src/config/typeorm.config.ts
  server/src/image/dto/ImageDTOs.ts
  server/src/image/image.module.ts
  server/src/image/service/image.service.ts
  server/src/main.ts
Labels: 🛰 Back, Priority: High

#85 feat: 색상 선택 관련 함수들 - #84
  client/utils/getAvgColor.ts
  client/utils/isSelectBlack.ts
Labels: 🚀 Front, Priority: Low

#90 feat: Footer 컴포넌트 구현
  client/assets/images/ic-github.png
  client/components/Footer/AboutUs.tsx
  client/components/Footer/index.tsx
  client/components/common/Layout.tsx
  client/pages/index.tsx
  client/styles/emotion.d.ts
Labels: 🚀 Front

#91 feat: artwork 서비스 부분 개선 및 ipfs 로직 추가 - #89
  server/.env.example
  server/.prettierrc
  server/package-lock.json
  server/package.json
  server/src/artwork/artwork.entity.ts
  server/src/artwork/artwork.module.ts
  server/src/artwork/artwork.repository.ts
  server/src/artwork/controller/artwork.controller.ts
  server/src/artwork/dto/artworkDTOs.ts
  server/src/artwork/service/artwork.service.ts
  server/src/auction/auction.entity.ts
  server/src/auction/auction.repository.ts
  server/src/image/service/image.service.ts
Labels: 🛰 Back

#92 feat: artwork 추가 > 내 artwork 보기(tile) 구현
  .gitignore
  client/.env
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/Tiles/ImageTile.tsx
  client/components/Artwork/Tiles/index.tsx
  client/components/Artwork/Uploader/index.tsx
  client/components/Footer/AboutUs.tsx
  client/components/Footer/index.tsx
  client/interfaces.ts
  client/utils/networking.ts
Labels: 🚀 Front

#95 feat: 헤더 바 구현 - #66
  client/assets/images/profile.png
  client/components/Header/headerStyles.tsx
  client/components/Header/index.tsx
  client/components/Header/style.ts
  client/components/Home/Pc.tsx
  client/pages/_document.tsx
  client/pages/artwork/post.tsx
  client/styles/emotion.d.ts
  client/styles/theme.ts
  client/utils/isMobile.ts
Labels: 🚀 Front, Priority: High

#96 feat: 로그인 페이지 레이아웃 - #94
  client/assets/images/google.png
  client/assets/images/kakao.png
  client/assets/images/login-side-test.png
  client/components/Login/LoginResultModal.tsx
  client/components/Login/SocialLoginButton.tsx
  client/components/Login/index.tsx
  client/package-lock.json
  client/package.json
  client/pages/_document.tsx
  client/pages/login/index.tsx
  client/styles/emotion.d.ts
  client/styles/theme.ts
Labels: 🚀 Front

#98 Fix: cors swagger - #97
  server/.env.example
  server/src/config/swagger.config.ts
  server/src/config/typeorm.config.ts
  server/src/main.ts
Labels: 🛰 Back

#99 feat: 소셜 로그인 API 구현 - #93
  client/.env.example
  client/.gitignore
  client/components/Login/SocialLoginButton.tsx
  client/components/Login/index.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/login/callback.tsx
  client/utils/networking.ts
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/artwork/artwork.module.ts
  server/src/artwork/controller/artwork.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/controller/auth.controller.ts
  server/src/auth/guard/CustomAuthGuard.ts
  server/src/auth/service/auth.service.ts
  server/src/main.ts
  server/src/user/controller/user.controller.ts
  server/src/user/service/user.service.ts
  server/src/user/user.module.ts
  server/src/user/user.repository.ts
Labels: 🚀 Front, 🛰 Back

#100 feat: 카드 컴포넌트 레이아웃 구현
  client/assets/images/ETH.png
  client/components/Card/index.tsx
  client/components/Card/style.ts
  client/components/Header/style.ts
  client/constants/card-type.ts
  client/styles/globals.css
  client/utils/isMobile.ts
Labels: 🚀 Front, Priority: High

#103 fix: 엔티티 및 Guard 코드 리팩토링 - #102
  server/src/artwork/artwork.module.ts
  server/src/auction/auction.entity.ts
  server/src/exhibition/exhibition.entity.ts
  server/src/exhibition/exhibition.module.ts
  server/src/user/user.module.ts
Labels: ⚒ Refactoring, 🛰 Back

#104 feat: 아트워크 post 페이지 api 연동 및 리팩토링 - #57
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/NewArtwork/index.tsx
  client/components/Artwork/Tiles/ImageTile.tsx
  client/components/Artwork/Tiles/index.tsx
  client/hooks/useInputArtwork.ts
  client/interfaces.ts
  client/pages/login/callback.tsx
  client/utils/networking.ts
  client/utils/parseCookie.ts
Labels: ⚒ Refactoring, 🚀 Front

#108 feat: 전시회 리스트 페이지 레이아웃 - #101
  client/components/Footer/index.tsx
  client/components/Header/headerStyles.tsx
  client/components/Header/style.ts
  client/components/common/Layout.tsx
  client/pages/exhibition/index.tsx
  client/styles/common.ts
Labels: 🚀 Front, Priority: High

#107 feat: 작품 추가 api 등록 - #106
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/ArtworkModal/style.ts
  client/hooks/useInputArtwork.ts
  client/hooks/useTest.ts
  client/interfaces.ts
  client/utils/networking.ts
  client/utils/parseCookie.ts
Labels: 🚀 Front

#112 feat: 전시회 리스트 조회 API 구현 - #109
  server/src/exhibition/controller/exhibition.controller.ts
  server/src/exhibition/exhibition.repository.ts
  server/src/exhibition/service/exhibition.service.ts
  server/src/exhibition/swagger/index.ts
Labels: 🛰 Back

#117 feat: MainPage - #67
  client/.babelrc
  client/assets/images/fake1.png
  client/assets/images/fake2.jpeg
  client/assets/images/fake3.jpg
  client/assets/images/fake4.png
  client/assets/images/fake43.png
  client/assets/images/fake5.jpeg
  client/components/Home/Pc.tsx
  client/components/Home/Pc/MainAuctionList.tsx
  client/components/Home/Pc/MainCarousel.tsx
  client/components/Home/Pc/NftInfo.tsx
  client/components/Home/Pc/index.tsx
  client/components/Home/Pc/styles.ts
  client/components/common/DeviceSwitch.tsx
  client/constants/fakeDatas.ts
  client/package-lock.json
  client/pages/index.tsx
  client/styles/common.ts
  client/tsconfig.json
  client/utils/getAvgColor.ts
  client/utils/isSelectBlack.ts
  client/utils/networking.ts
  client/utils/setColorFromImage.ts
Labels: 🚀 Front

#122 feat: 로그인 API 개선 및 로그아웃 API 구현 - #118
  server/src/auth/controller/auth.controller.ts
  server/src/auth/guard/CustomAuthGuard.ts
  server/src/auth/service/auth.service.ts
  server/src/auth/swagger/index.ts
  server/src/user/service/user.service.ts
  server/src/user/user.entity.ts
  server/src/user/user.repository.ts
Labels: 🛰 Back

#123 feat: 옥션 관련 apis 기능 개발 - #116
  server/.prettierrc
  server/src/app.module.ts
  server/src/auction/auction.module.ts
  server/src/auction/auction.repository.ts
  server/src/auction/controller/auction.controller.ts
  server/src/auction/dto/auctionDTOs.ts
  server/src/auction/service/auction.service.ts
  server/src/auction/swagger/index.ts
  server/src/config/typeorm.config.ts
Labels: 🛰 Back, Priority: High

#127 feat: exhibition 리스트 페이지 API 연결(필터), 잡다한 수정
  client/components/Artwork/Uploader/index.tsx
  client/components/Auction/AuctionList.tsx
  client/components/Card/style.ts
  client/components/Header/headerStyles.tsx
  client/pages/exhibition/index.tsx
  client/pages/exhibition/style.ts
  client/pages/login/index.tsx
  client/utils/networking.ts
  client/utils/parseCookie.ts
Labels: 🚀 Front

#131 feat: 경매 소켓 구현 - #119
  client/components/Auction/BidTable/index.tsx
  client/components/Auction/ItemDetail/index.tsx
  client/components/Auction/Trend/TrendHistory.tsx
  client/components/Auction/Trend/index.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/auction/[id].tsx
  client/store/GlobalStore.tsx
  client/utils/getRemainingTime.ts
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auction/auction.gateway.ts
  server/src/auction/auction.module.ts
  server/src/utils/sse/sse.controller.ts
  server/src/utils/sse/sse.module.ts
Labels: 🚀 Front, 🛰 Back

#126 feat: sql generator 생성 - #124
  .gitignore
  sqlGenerator/index.js
  sqlGenerator/package-lock.json
  sqlGenerator/package.json
Labels: TEST

#132 refactor: additional tasks
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/NewArtwork/index.tsx
  client/components/Artwork/Uploader/index.tsx
  client/components/Auction/AuctionList.tsx
  client/components/Header/headerStyles.tsx
  client/hooks/useControlModalPosition.ts
  client/hooks/useInputArtwork.ts
  client/pages/artwork/post.tsx
  client/utils/networking.ts
  server/package-lock.json
  server/src/auction/controller/auction.controller.ts
Labels: ⚒ Refactoring, 🚀 Front, 🛰 Back

#137 feat: DTO 유효성 검증 구현 - #136
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Home/Pc/MainCarousel.tsx
  client/hooks/useInputArtwork.ts
  server/package-lock.json
  server/package.json
  server/src/artwork/controller/artwork.controller.ts
  server/src/artwork/dto/artworkDTOs.ts
  server/src/artwork/service/artwork.service.ts
  server/src/auction/auction.repository.ts
  server/src/auction/controller/auction.controller.ts
  server/src/auth/controller/auth.controller.ts
  server/src/auth/dto/auth.credential.dto.ts
  server/src/auth/swagger/index.ts
  server/src/exhibition/exhibition.entity.ts
  server/src/exhibition/exhibition.repository.ts
Labels: 🛰 Back

#138 feat: 작품 좋아요 API 구현 - #129
  server/src/app.module.ts
  server/src/artwork/artwork.module.ts
  server/src/artwork/controller/artwork.controller.ts
  server/src/artwork/dto/artworkDTOs.ts
  server/src/artwork/swagger/index.ts
  server/src/interestArtwork/interestArtwork.module.ts
  server/src/interestArtwork/interestArtwork.repository.ts
  server/src/interestArtwork/interestArtwork.service.ts
Labels: 🛰 Back

#139 feat: post 아트워크 페이지 레이아웃
  client/components/Exhibition/LabelInput.tsx
  client/components/Exhibition/style.ts
  client/pages/exhibition/index.tsx
  client/pages/exhibition/post.tsx
Labels: 🚀 Front, Priority: High

#141 feat: 로그인 필요한 기능의 경우 모달 추가, api 싱크 안맞는 interface 수정 등 - #140
  client/components/Artwork/ArtworkModal/ArtworkFilter.tsx
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/NewArtwork/style.ts
  client/components/Auction/AuctionList.tsx
  client/components/Card/index.tsx
  client/components/Card/style.ts
  client/components/Home/Pc/MainCarousel.tsx
  client/components/Home/Pc/styles.ts
  client/components/common/RequireLoginModal.tsx
  client/constants/card-type.ts
  client/constants/fakeDatas.ts
  client/hooks/useControlModalPosition.ts
  client/hooks/useHandleRequireLoginModal.ts
  client/pages/artwork/result.tsx
  client/pages/exhibition/index.tsx
  client/utils/setColorFromImage.ts
  server/package-lock.json
Labels: 🚨 FIX, 🚀 Front, Priority: High

#143 feat: 에디터 초안 / 사각형 넣기 / 드래그 - #142
  client/components/Exhibition/Editor/EditorElement.tsx
  client/components/Exhibition/Editor/index.tsx
  client/components/Exhibition/Editor/utils.ts
  client/components/Home/Pc/styles.ts
Labels: 🚀 Front, 🌋 Important, Priority: High

#147 fix: 경매 작품, 전시회 DTO 개선 및 메인 페이지 API 연동 부분 개선 - #145
  client/components/Auction/AuctionList.tsx
  client/components/Home/Pc/MainAuctionList.tsx
  client/components/Home/Pc/MainCarousel.tsx
  client/components/Home/Pc/index.tsx
  client/components/Home/Pc/styles.ts
  client/components/common/Layout.tsx
  client/pages/index.tsx
  client/utils/networking.ts
  server/src/auction/auction.repository.ts
  server/src/auction/dto/auctionDTOs.ts
  server/src/exhibition/controller/exhibition.controller.ts
  server/src/exhibition/dto/exhibitionDTO.ts
  server/src/exhibition/exhibition.repository.ts
  server/src/exhibition/service/exhibition.service.ts
  server/src/exhibition/swagger/index.ts
Labels: 🚀 Front, 🛰 Back

#146 feat: 전시회 에디터 객체 색상 변경 기능 추가, TextBox 추가 기능 구현 - #134
  client/components/Exhibition/Editor/ColorPicker.tsx
  client/components/Exhibition/Editor/EditorElement.tsx
  client/components/Exhibition/Editor/index.tsx
  client/package-lock.json
  client/package.json
Labels: Priority: High

#151 feat: 작품 추가 결과 페이지 작업 및 소소한 오류수정 - #140
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/Tiles/ImageTile.tsx
  client/components/Artwork/Tiles/index.tsx
  client/components/Auction/CarouselItem.tsx/index.tsx
  client/hooks/useInputArtwork.ts
  client/interfaces.ts
  client/package-lock.json
  client/package.json
  client/pages/artwork/result.tsx
  client/pages/artwork/result/index.tsx
  client/pages/auction/curation/[id].tsx
Labels: 🚀 Front

#153 fix: 버그 수정- 카카오 연결끊기 로직, 내 모든 작품 조회 수정
  server/src/auth/service/auth.service.ts
  server/src/user/controller/user.controller.ts
Labels: 🚨 FIX

#156 feat: 마이페이지 API 구현 - #148
  server/src/artwork/artwork.repository.ts
  server/src/artwork/controller/artwork.controller.ts
  server/src/artwork/service/artwork.service.ts
  server/src/artwork/swagger/index.ts
  server/src/exhibition/exhibition.repository.ts
  server/src/user/controller/user.controller.ts
  server/src/user/dto/userDTO.ts
  server/src/user/service/user.service.ts
  server/src/user/swagger/index.ts
  server/src/user/user.module.ts
Labels: 🛰 Back

#157 feat: element 선택 , 주변 선 ,주변 점 - #134
  client/components/Exhibition/Editor/EditorElement.tsx
  client/components/Exhibition/Editor/index.tsx
  client/components/Exhibition/Editor/utils.ts
  client/pages/exhibition/editor.tsx
Labels: 🚀 Front, Priority: High

#158 feat: 여태 작업한 에디터 페이지에 부착, 내부페이지 라우팅 - #134
  client/components/Exhibition/ArtworkSelector/Selector.tsx
  client/components/Exhibition/ArtworkSelector/index.tsx
  client/components/Exhibition/Editor/Editor.tsx
  client/components/Exhibition/Editor/EditorElement.tsx
  client/components/Exhibition/Editor/index.tsx
  client/components/Exhibition/Editor/types.ts
  client/components/Exhibition/Editor/utils.ts
  client/components/Exhibition/Form/index.tsx
  client/components/Exhibition/style.ts
  client/constants/editor-initial-state.ts
  client/pages/exhibition/edit.tsx
  client/pages/exhibition/editor.tsx
  client/pages/exhibition/post.tsx
Labels: ⚒ Refactoring, 🚀 Front, Priority: High

#159 feat: 마우스 커서 변경, editor 페이지에서 컴포넌트로 변경
  client/components/Exhibition/Editor/EditorElement.tsx
  client/components/Exhibition/Editor/utils.ts
Labels: ⚒ Refactoring, 🚀 Front

#162 feat: 전시회 에디터 이미지 추가 기능 구현 - #134
  client/.babelrc
  client/assets/images/chevron-left.png
  client/assets/images/chevron-right.png
  client/assets/images/editor-backward.png
  client/assets/images/editor-color.png
  client/assets/images/editor-forward.png
  client/assets/images/editor-line.png
  client/assets/images/editor-rectangular.png
  client/assets/images/editor-text.png
  client/components/Artwork/Tiles/ImageTile.tsx
  client/components/Exhibition/ArtworkSelector/Selector.tsx
  client/components/Exhibition/ArtworkSelector/index.tsx
  client/components/Exhibition/Editor/Editor.tsx
  client/components/Exhibition/Editor/EditorElement.tsx
  client/components/Exhibition/Editor/ImageSlider.tsx
  client/components/Exhibition/Editor/index.tsx
  client/components/Exhibition/Editor/types.ts
  client/constants/editor-initial-state.ts
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/store/editorImageState.ts
  client/tsconfig.json
Labels: 🚀 Front, Priority: High

#163 refactor: 옥션 디테일 페이지 개선 - #160
  client/components/Auction/BidTable/index.tsx
  client/components/Auction/ItemDetail/AboutArtist.tsx
  client/components/Auction/ItemDetail/ArtworkDetail.tsx
  client/components/Auction/ItemDetail/index.tsx
  client/components/Auction/Trend/TrendHistory.tsx
  client/components/Auction/Trend/index.tsx
  client/interfaces.ts
  client/pages/auction/[id].tsx
  client/tsconfig.json
  client/utils/getRemainingTime.ts
  client/utils/time.ts
  server/src/app.module.ts
  server/src/auction/auction.gateway.ts
  server/src/auction/auction.module.ts
  server/src/auction/auction.repository.ts
  server/src/auction/dto/auctionDTOs.ts
  server/src/auctionHistory/auctionHistory.module.ts
  server/src/auctionHistory/auctionHistory.repository.ts
  server/src/auctionHistory/auctionHistory.service.ts
Labels: ⚒ Refactoring, 🚀 Front, 🛰 Back

#165 fix: 칸반보드에 보고된 오류 수정
  client/components/Card/style.ts
  client/components/Exhibition/Editor/index.tsx
  client/components/Header/headerStyles.tsx
  client/pages/auction/[id].tsx
  client/pages/exhibition/[id].tsx
  client/pages/exhibition/post.tsx
  client/pages/mypage/index.tsx
Labels: 🚨 FIX, 🚀 Front

#166 Fix: css 간단 수정과 sql 제너레이터 개선
  client/components/Artwork/ArtworkModal/ArtworkFilter.tsx
  client/components/Artwork/ArtworkModal/style.ts
  client/components/Artwork/NewArtwork/index.tsx
  client/components/Artwork/NewArtwork/style.ts
  client/components/Auction/AuctionList.tsx
  client/components/Card/style.ts
  client/components/Exhibition/style.ts
  sqlGenerator/README.md
  sqlGenerator/index.js
Labels: 🚨 FIX

#167 feat: Resize 1차 구현 완료
  client/components/Exhibition/Editor/EditorElement.tsx
  client/components/Exhibition/Editor/resizeFunctions.ts
  client/components/Exhibition/Editor/utils.ts
Labels: 🚀 Front, Priority: High

#169 fix: #134 - resize시 dots 오류 해결 / selectable 수정 / input 반쪽 해결
  client/components/Exhibition/Editor/Editor.tsx
  client/components/Exhibition/Editor/EditorElement.tsx
  client/components/Exhibition/Editor/utils.ts
  client/package-lock.json
  client/store/GlobalStore.tsx
Labels: 🚨 FIX, 🚀 Front, 🌋 Important, Priority: High

#170 refactor: 클라이언트 디렉토리 구조 정리, 카드 lazy loading 추가
  client/assets/images/fallback-image.png
  client/components/Artwork/ArtworkFilter/index.tsx
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/ImageTile/index.tsx
  client/components/Artwork/Tiles/index.tsx
  client/components/Auction/AboutArtist/index.tsx
  client/components/Auction/ArtworkDetail/index.tsx
  client/components/Auction/AuctionList.tsx
  client/components/Auction/ItemDetail/index.tsx
  client/components/Auction/Trend/index.tsx
  client/components/Auction/TrendHistory/index.tsx
  client/components/Exhibition/ArtworkSelector/Selector.tsx
  client/components/Exhibition/ArtworkSelector/index.tsx
  client/components/Exhibition/ArtworkSelector/style.tsx
  client/components/Exhibition/ArtworkSelectorWrapper/index.tsx
  client/components/Exhibition/EditorPage/ColorPicker/index.tsx
  client/components/Exhibition/EditorPage/Editor/index.tsx
  client/components/Exhibition/EditorPage/Editor/style.tsx
  client/components/Exhibition/EditorPage/Editor/types.ts
  client/components/Exhibition/EditorPage/EditorElement/index.tsx
  client/components/Exhibition/EditorPage/EditorElement/resizeFunctions.ts
  client/components/Exhibition/EditorPage/EditorElement/utils.ts
  client/components/Exhibition/EditorPage/ImageSlider/index.tsx
  client/components/Exhibition/EditorPage/index.tsx
  client/components/Exhibition/FormPage/Preview/Preview.tsx
  client/components/Exhibition/FormPage/index.tsx
  client/components/Exhibition/LabelInput/index.tsx
  client/components/Exhibition/ListFilter/index.tsx
  client/components/Home/Pc/MainAuctionList.tsx
  client/components/Login/LoginResultModal/index.tsx
  client/components/Login/SocialLoginButton/index.tsx
  client/components/common/Card/LazyImage/index.tsx
  client/components/common/Card/index.tsx
  client/components/common/Card/style.ts
  client/components/common/RequireLoginModal.tsx
  client/components/common/RequireLoginModal/index.tsx
  client/components/common/RequireLoginModal/style.ts
  client/next.config.js
  client/pages/exhibition/index.tsx
  client/pages/exhibition/post.tsx
Labels: ⚒ Refactoring, 🚀 Front

#172 feat: infinite scroll 추가 - #105
  client/components/Auction/AuctionList/index.tsx
  client/components/Exhibition/ExhibitionList/index.tsx
  client/components/Exhibition/style.ts
  client/components/Home/Pc/MainCarousel.tsx
  client/components/common/Card/LazyImage/index.tsx
  client/hooks/useInfiniteScroll.ts
  client/pages/exhibition/index.tsx
Labels: 🚀 Front

#176 feat: 전시회 API 구현 및 돋보기 기능 개선 - #175
  client/pages/auction/[id].tsx
  server/package-lock.json
  server/package.json
  server/src/exhibition/controller/exhibition.controller.ts
  server/src/exhibition/dto/exhibitionDTO.ts
  server/src/exhibition/service/exhibition.service.ts
  server/src/exhibition/swagger/index.ts
  server/src/main.ts
Labels: 🚀 Front, 🛰 Back

#179 feat: artwork 등록 결과 페이지 레이아웃 작업 - #173
  client/components/Artwork/ResultDetail/index.tsx
  client/pages/artwork/result/index.tsx
  client/utils/networking.ts
Labels: 🚀 Front, Priority: High

#178 feat: translate 교체 / unselect / 리스너 통합 / 포커스
  client/components/Exhibition/EditorPage/Editor/index.tsx
  client/components/Exhibition/EditorPage/EditorElement/index.tsx
  client/components/Exhibition/EditorPage/EditorElement/resizeFunctions.ts
  client/components/Exhibition/EditorPage/EditorElement/utils.ts
  client/components/Home/Pc/MainCarousel.tsx
Labels: 🚀 Front, Priority: High

#180 feat: nft 프로젝트 생성 - #174
  .gitignore
  nft/.env.example
  nft/README.md
  nft/contracts/Migrations.sol
  nft/contracts/SalonDesRefuse.sol
  nft/migrations/1_initial_migration.js
  nft/migrations/2_sdr_migration.js
  nft/package-lock.json
  nft/package.json
  nft/test/.gitkeep
  nft/truffle-config.js
  server/.env.example
Labels: 🛰 Back, Priority: High

#186 feat: #171 - 이미지 리사이즈 / input 드래거블
  client/components/Exhibition/EditorPage/Editor/index.tsx
  client/components/Exhibition/EditorPage/EditorElement/index.tsx
  client/components/Exhibition/EditorPage/EditorElement/utils.ts
  server/package-lock.json
Labels: 🚀 Front, Priority: High

#183 feat: smart contract 호출 및 토큰 생성 확인
  .gitignore
  client/components/Artwork/ResultDetail/index.tsx
  client/ethereum.d.ts
  client/pages/artwork/result/index.tsx
  client/public/ethereum/abi.json
  client/public/ethereum/address.json
  nft/migrations/1_initial_migration.js
  nft/migrations/2_sdr_migration.js
  nft/package-lock.json
  nft/truffle-config.js
  server/package-lock.json
  server/package.json
Labels: 🚀 Front, Priority: High

#189 feat: 경매 페이지 개선, 경매 로직 개선 - #177
  client/assets/images/checked.png
  client/assets/images/failed.png
  client/components/Auction/BidTable/index.tsx
  client/components/Auction/ItemDetail/index.tsx
  client/components/Auction/Trend/index.tsx
  client/components/common/Layout.tsx
  client/components/common/Toast/index.tsx
  client/constants/eth.ts
  client/hooks/useMagnifier.ts
  client/pages/auction/[id].tsx
  client/public/ethereum/abi.json
  client/public/ethereum/address.json
  client/store/GlobalStore.tsx
  client/store/auctionSocketState.ts
  client/store/editorImageState.ts
  client/store/toastState.ts
  client/utils/time.ts
  server/src/auction/auction.gateway.ts
Labels: 🚀 Front, 🛰 Back, Priority: High

#191 feat: 경매 1분 이하 입찰시 시간 다시 설정 - #185
  .gitignore
  server/src/auction/auction.gateway.ts
  server/src/auction/service/auction.service.ts
Labels: 🛰 Back, Priority: Middle

#192 feat: 특정 전시회 조회 API, 종료된 경매 처리 API - #188
  server/src/app.module.ts
  server/src/auction/auction.module.ts
  server/src/auction/auction.repository.ts
  server/src/auction/service/auction.service.ts
  server/src/auctionHistory/auctionHistory.repository.ts
  server/src/auctionHistory/auctionHistory.service.ts
  server/src/completedAuction/completedAuction.entity.ts
  server/src/completedAuction/completedAuction.module.ts
  server/src/completedAuction/completedAuction.repository.ts
  server/src/completedAuction/completedAuction.service.ts
  server/src/exhibition/controller/exhibition.controller.ts
  server/src/exhibition/exhibition.repository.ts
  server/src/exhibition/service/exhibition.service.ts
  server/src/exhibition/swagger/index.ts
Labels: 🛰 Back

#193 Fix/#187 exhibition bug
  client/components/Exhibition/EditorPage/index.tsx
  client/hooks/useInputExhibition.ts
  client/interfaces.ts
  client/pages/exhibition/[id].tsx
  client/utils/networking.ts
  server/src/auction/service/auction.service.ts
  server/src/exhibition/controller/exhibition.controller.ts
Labels: 🚀 Front

#190 feat: 끝난 경매 스케쥴 잡 처리 - #181
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/artwork/artwork.entity.ts
  server/src/artwork/artwork.repository.ts
  server/src/artwork/service/artwork.service.ts
  server/src/auction/auction.entity.ts
  server/src/auction/auction.module.ts
  server/src/auction/auction.repository.ts
  server/src/auction/controller/auction.controller.ts
  server/src/auction/service/auction.service.ts
  server/src/auctionHistory/auctionHistory.entity.ts
  server/src/cronTask/crontask.module.ts
  server/src/cronTask/crontask.service.ts
Labels: 🛰 Back, Priority: High

#198 feat: nftToken 저장 API 및 전시회 테이블 size 필드 추가
  client/interfaces.ts
  client/pages/artwork/result/index.tsx
  server/src/artwork/artwork.entity.ts
  server/src/artwork/artwork.repository.ts
  server/src/artwork/controller/artwork.controller.ts
  server/src/artwork/dto/artworkDTOs.ts
  server/src/artwork/service/artwork.service.ts
  server/src/artwork/swagger/index.ts
  server/src/exhibition/dto/exhibitionDTO.ts
  server/src/exhibition/exhibition.entity.ts
  server/src/exhibition/exhibition.repository.ts
  server/src/exhibition/swagger/index.ts
Labels: 🛰 Back

#202 feat: 마이페이지 작업 및 세션 로직 수정 - #195
  client/.prettierrc.json
  client/assets/images/checked.png
  client/assets/images/failed.png
  client/assets/images/mypage-profile.png
  client/components/Auction/AuctionList/index.tsx
  client/components/Auction/BidTable/index.tsx
  client/components/Exhibition/style.ts
  client/components/Header/headerStyles.tsx
  client/components/Header/index.tsx
  client/components/Header/style.ts
  client/components/MyPage/ArtworkPage/index.tsx
  client/components/MyPage/AuctionPage/AuctionList/index.tsx
  client/components/MyPage/AuctionPage/index.tsx
  client/components/MyPage/Exhibition/index.tsx
  client/components/MyPage/FavoritePage/index.tsx
  client/components/MyPage/Filter/index.tsx
  client/components/MyPage/Modal/index.tsx
  client/components/MyPage/ProfilePage/ProfileImage/index.tsx
  client/components/MyPage/ProfilePage/index.tsx
  client/components/MyPage/Sidebar/index.tsx
  client/components/common/Layout.tsx
  client/components/common/Toast/index.tsx
  client/hooks/useHandleRequireLoginModal.ts
  client/interfaces.ts
  client/package-lock.json
  client/package.json
  client/pages/auction/[id].tsx
  client/pages/exhibition/index.tsx
  client/pages/mypage/index.tsx
  client/store/sessionState.ts
  client/store/toastState.ts
  client/utils/networking.ts
Labels: 🚀 Front, Priority: Middle

#203 feat: 전시 상세 페이지 레이아웃 - #184
  client/components/Exhibition/EditorPage/Editor/index.tsx
  client/components/Exhibition/EditorPage/Editor/types.ts
  client/components/Exhibition/EditorPage/EditorElement/index.tsx
  client/components/Exhibition/EditorPage/index.tsx
  client/components/Exhibition/ExhbitionDetail/ExhibitionContents.tsx
  client/components/Exhibition/ExhbitionDetail/index.tsx
  client/hooks/useInputExhibition.ts
  client/interfaces.ts
  client/pages/exhibition/[id].tsx
  client/utils/networking.ts
Labels: 🚀 Front, Priority: High

#204 fix: 백엔드 API 개선
  client/components/Auction/BidTable/index.tsx
  client/interfaces.ts
  client/pages/auction/[id].tsx
  client/public/ethereum/abi.json
  client/public/ethereum/address.json
  client/utils/networking.ts
  server/src/artwork/artwork.entity.ts
  server/src/artwork/artwork.repository.ts
  server/src/artwork/dto/artworkDTOs.ts
  server/src/auction/auction.gateway.ts
  server/src/auctionHistory/auctionHistory.entity.ts
  server/src/auctionHistory/auctionHistory.repository.ts
  server/src/auctionHistory/auctionHistory.service.ts
  server/src/completedAuction/completedAuction.entity.ts
  server/src/completedAuction/completedAuction.service.ts
  server/src/cronTask/ethereum/abi.json
  server/src/cronTask/ethereum/address.json
  server/src/user/controller/user.controller.ts
  server/src/user/service/user.service.ts
  server/src/user/user.module.ts
Labels: 🚨 FIX, 🛰 Back

#219 feat: 마이페이지 남은 작업 및 내 보유 작품 조회 - #195
  client/components/Artwork/Tiles/index.tsx
  client/components/Artwork/Uploader/index.tsx
  client/components/Auction/AuctionList/index.tsx
  client/components/Auction/BidTable/index.tsx
  client/components/Exhibition/ExhibitionList/index.tsx
  client/components/Header/index.tsx
  client/components/MyPage/ArtworkPage/BoughtArtworkPage/index.tsx
  client/components/MyPage/ArtworkPage/index.tsx
  client/components/MyPage/AuctionPage/index.tsx
  client/components/MyPage/Exhibition/index.tsx
  client/components/MyPage/FavoritePage/index.tsx
  client/components/MyPage/Filter/index.tsx
  client/components/MyPage/ProfilePage/index.tsx
  client/components/common/Card/index.tsx
  client/hooks/useInputArtwork.ts
  client/hooks/useInputExhibition.ts
  client/pages/artwork/result/index.tsx
  client/pages/mypage/index.tsx
  client/public/ethereum/abi.json
  client/public/ethereum/address.json
  client/store/sessionState.ts
  client/utils/networking.ts
  nft/contracts/SalonDesRefuse.sol
  server/src/cronTask/ethereum/abi.json
  server/src/cronTask/ethereum/address.json
Labels: 🚀 Front, Priority: Middle

#221 fix: 경매 작품 조회 API 수정
  client/components/Auction/ItemDetail/index.tsx
  client/components/Auction/TrendHistory/index.tsx
  server/src/auction/auction.gateway.ts
  server/src/auction/auction.repository.ts
  server/src/auction/dto/auctionDTOs.ts
  server/src/auctionHistory/auctionHistory.entity.ts
  server/src/auctionHistory/auctionHistory.module.ts
  server/src/auctionHistory/auctionHistory.service.ts
  server/src/completedAuction/completedAuction.entity.ts
  server/src/completedAuction/completedAuction.service.ts
  server/src/user/controller/user.controller.ts
  server/src/user/swagger/index.ts
Labels: 🚀 Front, 🛰 Back

#222 fix: 현재 거래중인 작품 조회 api 쿼리 수정
  server/src/artwork/artwork.repository.ts
  server/src/auctionHistory/auctionHistory.repository.ts
  server/src/user/service/user.service.ts
Labels: 🚨 FIX

#223 feat: 텍스트 스타일링
  client/assets/images/fake1.png
  client/assets/images/fake11.png
  client/assets/images/fake2.jpeg
  client/assets/images/fake3.jpg
  client/assets/images/fake4.png
  client/assets/images/fake43.png
  client/assets/images/fake5.jpeg
  client/assets/images/font-styling.png
  client/assets/images/text-align-center.png
  client/assets/images/text-align-left.png
  client/assets/images/text-align-right.png
  client/components/Exhibition/EditorPage/Editor/index.tsx
  client/components/Exhibition/EditorPage/EditorElement/index.tsx
  client/components/Exhibition/EditorPage/FontStyler/index.tsx
  client/components/Header/style.ts
  client/interfaces.ts
  client/public/ethereum/abi.json
  client/public/ethereum/address.json
  server/src/cronTask/ethereum/abi.json
  server/src/cronTask/ethereum/address.json
Labels: 🚀 Front, Priority: High

#225 fix: 이미지 z-index 수정시에 선택이 안되던 오류 해결
  client/components/Exhibition/EditorPage/Editor/index.tsx
  client/components/Exhibition/EditorPage/EditorElement/index.tsx
Labels: 🚨 FIX, 🚀 Front

#231 refactor: 리뷰받은 내용 수정 - #227
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/NewArtwork/index.tsx
  client/components/Artwork/Tiles/index.tsx
  client/components/Auction/AuctionList/index.tsx
  client/components/Exhibition/ArtworkSelector/index.tsx
  client/components/Exhibition/ExhibitionList/index.tsx
  client/components/MyPage/ArtworkPage/BoughtArtworkPage/index.tsx
  client/components/MyPage/AuctionPage/index.tsx
  client/components/MyPage/Exhibition/index.tsx
  client/components/MyPage/ProfilePage/index.tsx
  client/components/common/Fallback/index.tsx
  client/hooks/useArtworkInput.ts
  client/hooks/useInputArtwork.ts
  client/hooks/useInputExhibition.ts
  client/hooks/useInputProfile.ts
  client/pages/artwork/result/index.tsx
  client/pages/auction/[id].tsx
  client/pages/exhibition/[id].tsx
  client/pages/index.tsx
  client/pages/login/callback.tsx
  client/pages/mypage/index.tsx
  client/service/networking.ts
  client/store/sessionState.ts
  client/tsconfig.json
Labels: ⚒ Refactoring, 🚀 Front

#242 feat: Suspense & ErrorBoundary 직접 구현
  client/components/Artwork/Tiles/index.tsx
  client/components/Exhibition/ExhbitionDetail/ExhibitionContents.tsx
  client/components/MyPage/ArtworkPage/BoughtArtworkPage/index.tsx
  client/components/MyPage/ArtworkPage/index.tsx
  client/components/MyPage/Filter/index.tsx
  client/components/MyPage/ProfilePage/index.tsx
  client/components/common/ErrorBoundary.tsx
  client/components/common/Fallback.tsx
  client/components/common/Suspense.tsx
  client/utils/createResource.ts
Labels: 🚀 Front

#244 feat: 경매 캐러셀 추가 및 소소한 리팩토링 - #232
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/NewArtwork/index.tsx
  client/components/Auction/AuctionList/index.tsx
  client/components/Auction/BidTable/index.tsx
  client/components/Auction/Carousel/index.tsx
  client/components/Auction/CarouselItem.tsx/index.tsx
  client/components/Auction/ItemDetail/index.tsx
  client/components/Exhibition/ArtworkSelector/index.tsx
  client/components/Exhibition/ArtworkSelector/style.ts
  client/components/Exhibition/ArtworkSelectorWrapper/index.tsx
  client/components/Exhibition/ExhibitionList/index.tsx
  client/components/Home/Pc/MainCarousel.tsx
  client/components/MyPage/ProfilePage/index.tsx
  client/components/MyPage/Sidebar/index.tsx
  client/components/common/Card/LazyImage/index.tsx
  client/components/common/Fallback.tsx
  client/components/common/Suspense.tsx
  client/constants/curations.ts
  client/hooks/useControlModalPosition.ts
  client/hooks/useInputArtwork.ts
  client/hooks/useInputExhibition.ts
  client/hooks/useToast.ts
  client/pages/auction/curation/george.tsx
  client/pages/auction/curation/imnotmoon.tsx
  client/pages/auction/curation/reasonable.tsx
  client/pages/auction/curation/series.tsx
  client/service/networking.ts
  client/styles/globals.css
Labels: ⚒ Refactoring, 🚀 Front, Priority: High

#251 fix: 이슈 #250에 기재된 버그 수정
  client/components/Artwork/Tiles/index.tsx
  client/components/Artwork/Uploader/index.tsx
  client/components/Auction/AuctionList/index.tsx
  client/components/Auction/BidTable/index.tsx
  client/components/Exhibition/ArtworkSelector/index.tsx
  client/components/Exhibition/EditorPage/ImageSlider/index.tsx
  client/components/Exhibition/FormPage/index.tsx
  client/components/Exhibition/ListFilter/index.tsx
  client/components/Exhibition/style.ts
  client/components/Header/headerStyles.tsx
  client/components/Header/index.tsx
  client/components/Header/style.ts
  client/components/MyPage/ProfilePage/index.tsx
  client/components/common/Fallback/index.tsx
  client/components/common/Layout.tsx
  client/components/common/Modal/index.tsx
  client/components/common/RequireLoginModal/index.tsx
  client/components/common/RequireLoginModal/style.ts
  client/components/common/Toast/index.tsx
  client/hooks/useArtworkInput.ts
  client/hooks/useHandleRequireLoginModal.ts
  client/package-lock.json
  client/package.json
  client/pages/artwork/result/index.tsx
  client/pages/auction/[id].tsx
  client/pages/exhibition/index.tsx
  client/store/modalState.ts
Labels: 🚨 FIX, 🚀 Front

#255 [BUG] NFT 관련 버그 수정
  client/components/Auction/BidTable/index.tsx
  client/constants/toast-message.ts
  client/next.config.js
  nft/.env.example
  nft/build/address/SalonDesRefusesAddress.json
  nft/build/address/devAddress.json
  nft/build/address/prodAddress.json
  nft/build/contracts/Migrations.json
  nft/build/contracts/SalonDesRefuse.json
  nft/contracts/Migrations.sol
  nft/contracts/SalonDesRefuse.sol
  nft/deploy_dev.sh
  nft/deploy_prod.sh
  nft/migrations/1_initial_migration.js
  nft/migrations/1_sdr_migration.js
  nft/migrations/2_sdr_migration.js
  nft/package.json
  nft/truffle-config.js
  server/.env.example
  server/src/auction/auction.service.ts
  server/src/auction/gateway/auction.gateway.ts
  server/src/auctionHistory/auctionHistory.repository.ts
  server/src/completedAuction/completedAuction.service.ts
  server/src/cronTask/crontask.controller.ts
  server/src/cronTask/crontask.service.ts
Labels: 🚨 FIX

#258 fix: 여러 버그 수정
  client/components/Auction/AuctionList/index.tsx
  client/components/Auction/BidTable/index.tsx
  client/components/Exhibition/EditorPage/Editor/index.tsx
  client/components/Exhibition/EditorPage/Editor/style.tsx
  client/components/Exhibition/EditorPage/EditorElement/index.tsx
  client/components/Exhibition/ExhibitionList/index.tsx
  client/components/Home/Pc/NftInfo.tsx
  client/components/Home/Pc/styles.ts
  client/public/icons/nft.png
  server/src/artwork/artwork.repository.ts
  server/src/auth/auth.service.ts
  server/src/exhibition/exhibition.controller.ts
  server/src/exhibition/exhibition.service.ts
Labels: 🚨 FIX

#260 Fix/#259 buglist2
  client/components/Artwork/ArtworkModal/index.tsx
  client/components/Artwork/NewArtwork/index.tsx
  client/components/Artwork/ResultDetail/index.tsx
  client/components/Artwork/Uploader/index.tsx
  client/components/Auction/ItemDetail/index.tsx
  client/components/Exhibition/ArtworkSelectorWrapper/index.tsx
  client/components/Header/headerStyles.tsx
  client/components/Header/index.tsx
  client/hooks/useArtworkInput.ts
  client/package-lock.json
  client/package.json
  client/pages/_document.tsx
  client/pages/auction/[id].tsx
  client/pages/exhibition/[id].tsx
  client/pages/exhibition/post.tsx
Labels: 🚨 FIX, 🚀 Front, Priority: High
